name: arbiter_mock_server
description: A Flutter app for intercepting and mocking network requests
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # HTTP Client
  http: ^1.1.0

  # Storage
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.5.3

  # JSON
  json_annotation: ^4.8.1

  # File Picker
  file_picker: ^10.3.3
  share_plus: ^7.2.1
  cross_file: ^0.3.4+2

  # UI
  cupertino_icons: ^1.0.6
  intl: ^0.18.1

  # Dependency Injection
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/app_icon/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/app_icon.png
    - assets/